---
- name: '[Ubuntu] Include vars'
  include_vars: postgresql_ubuntu.yml

- name: '[Ubuntu] Install pgdg package signing key'
  apt_key: keyserver=pgp.mit.edu id=ACCC4CF8
  
- name: '[Ubuntu] Install repository'
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main'
    update_cache: yes

- name: '[Ubuntu] Install postgresql {{ postgresql_version }}'
  apt:
    name: "postgresql{{ '-' ~ postgresql_version if postgresql_version is defined else '' }}"

- name: '[Ubuntu] Ensure pgdata directory not exists'
  stat:
    path: '{{ postgresql_pgdata }}/base'
  register: pgdata_stat
  failed_when: false

- name: '[Ubuntu] PostgreSQL initdb creates a new database cluster'
  shell: "/usr/lib/postgresql/{{ postgresql_version }}/bin/pg_ctl -D {{ postgresql_pgdata }} initb"
  become: yes
  become_user: postgres

- name: '[EL] Start PostgreSQL server'
  shell: '/usr/lib/postgresql/{{ postgresql_version }}/bin/pg_ctl -D {{ postgresql_pgdata }} -w start'
  become: yes
  become_user: postgres
