---
- name: '[EL] Include vars'
  include_vars: postgresql_redhat.yml

- name: '[EL] Install repository'
  yum:
    name: '{{ postgresql_yum_repository_url }}'
    state: present

- name: '[EL] Install postgresql {{ postgresql_version }}'
  yum:
    name: 'postgresql{{ postgresql_version_terse }}-server'
    state: present

- name: '[EL] PostgreSQL initdb creates a new database cluster'
  shell: "/usr/pgsql-{{ postgresql_version }}/bin/postgresql{{ postgresql_version_terse }}-setup initdb"
