---

- name: '[EL] Install repository'
    yum: '{{ postgresql_yum_repository_url }}'
    state: present

- name: '[EL] Install postgresql {{ postgresql_version }}'
    yum: 'postgresql{{ postgresql_version_terse }}-server'
    state: present

- name: '[EL] PostgreSQL initdb creates a new database cluster'
  shell: "/usr/pgsql-{{ postgresql_version }}/bin/postgresql{{ postgresql_version_terse }}-setup initdb"
